<?php

declare(strict_types=1);

namespace Deployer;

use Symfony\Component\Console\Input\InputOption;

use function ChristianHuth\Typo3Deployer\dumpDatabase;
use function ChristianHuth\Typo3Deployer\locateBinary;

// Downloads database and fileadmin of a TYPO3 project from a Deployer host. Works standalone on top of
// any Deployer config (e.g. Deployer's own recipe/typo3.php) and is included by recipe/deploy.php.
//
//   dep sync:download <host>                         fresh DB dump + fileadmin
//   dep sync:db:download <host> --use-existing-db-dump   newest dump left by typo3:database:export

require_once 'recipe/common.php';
require_once __DIR__ . '/../src/functions.php';

option('use-existing-db-dump', null, InputOption::VALUE_NONE, 'sync:db:download: download the newest existing dump (see sync_existing_db_dumps) instead of creating a fresh one');

if (!has('typo3_webroot')) {
    set('typo3_webroot', 'public');
}

// Remote TYPO3 project root the DB credentials are read from (config/system/settings.php)
set('sync_typo3_root', '{{current_path}}');
set('sync_fileadmin_path', '{{deploy_path}}/shared/{{typo3_webroot}}/fileadmin');
// Glob of the dumps typo3:database:export writes on every deploy, used by --use-existing-db-dump
set('sync_existing_db_dumps', '{{deploy_path}}/shared/dbbackup-*.sql*');
// Tables dumped without their rows (shell patterns) - TYPO3 rebuilds them on its own
set('sync_db_structure_only_tables', ['cache_*', 'cf_*', 'be_sessions', 'fe_sessions']);
// Processed images and temp files are regenerated by TYPO3 on demand, no need to transfer them
set('sync_files_exclude', ['_processed_/', '_temp_/']);
// Local target: db.sql.gz and files/ - the layout "ddev pull" expects
set('sync_local_dir', '.ddev/.downloads');

set('bin/mysqldump', fn () => locateBinary('mysqldump', 'mariadb-dump'));
set('bin/mysql', fn () => locateBinary('mysql', 'mariadb'));

desc('Download a database dump into {{sync_local_dir}}/db.sql.gz (fresh unless --use-existing-db-dump)');
task('sync:db:download', function () {
    $localDir = get('sync_local_dir');
    runLocally('mkdir -p ' . escapeshellarg($localDir));
    $target = $localDir . '/db.sql.gz';

    if (input()->getOption('use-existing-db-dump')) {
        $latest = run('ls -t {{sync_existing_db_dumps}} 2>/dev/null | head -1 || true');
        if ($latest === '') {
            throw error('No existing database dump matches {{sync_existing_db_dumps}}');
        }
        info("Using existing dump <info>{$latest}</info>");
        // rsync compresses in transit anyway, so plain .sql dumps get gzipped locally instead of
        // writing a compressed copy on the remote host
        if (str_ends_with($latest, '.gz')) {
            download($latest, $target);
        } else {
            download($latest, $localDir . '/db.sql');
            runLocally('gzip -f ' . escapeshellarg($localDir . '/db.sql'));
        }
        return;
    }

    info('Creating a fresh database dump');
    $tmpDir = run('mktemp -d');
    try {
        dumpDatabase(get('sync_typo3_root'), "{$tmpDir}/db.sql.gz", get('sync_db_structure_only_tables'));
        download("{$tmpDir}/db.sql.gz", $target);
    } finally {
        run("rm -rf {$tmpDir}");
    }
});

desc('Download fileadmin into {{sync_local_dir}}/files');
task('sync:files:download', function () {
    $target = get('sync_local_dir') . '/files/';
    runLocally('mkdir -p ' . escapeshellarg($target));
    $options = ['--delete'];
    foreach (get('sync_files_exclude') as $exclude) {
        $options[] = '--exclude=' . $exclude;
    }
    download('{{sync_fileadmin_path}}/', $target, ['options' => $options]);
});

desc('Download database dump and fileadmin');
task('sync:download', [
    'sync:db:download',
    'sync:files:download',
]);
